### ISSUE TITLE
"[HMR] bundle rebuilding" is running on and on

### ISSUE THREAD

**Issue by skorunka** [asadsahi/AspNetCoreSpa#104] opened 2017-05-15 09:28 UTC
When I run the app for the 1st time everything is OK. Bundles are generated etc..

After a simple change in client side code, the HMR rebuild the component but does not stop:

![image](https://cloud.githubusercontent.com/assets/218913/26051056/e7e45932-3958-11e7-840c-34b48b4c7dd2.png)

I have to shut down IISExpress/host and run application again.

I don't see any errors in the console, tslint has no errors, webpack builds without any errors.

Wny ida why is this happening?

**Comment by robertcck** [comment] 2017-05-15 10:09
I had the same issue, cpu and memory are up high as a result. 
I turned off HotModuleReplacement to resolve this issue

**Comment by skorunka** [comment] 2017-05-16 13:31
@robertcck Yep, that's the only solution I found. BTW do you use primeng? I read in other discussions that it might actually cause the HMR issue.

**Comment by j-nord** [comment] 2017-05-17 14:45
When copy our app code in app folder we have the same issue.

**Comment by m2017atTR** [comment] 2017-06-09 10:28
Hello again,
  this happened when i added/imported css in vendor,
i am not sure what couses your problem to happen but i just wanted to notice.

for example, this actions made my situation same HMR build again and again, 
     when using primeng its css coused some problems..
     when i tryed to add custom angular material theme like exactly described on their site.

good luck

**Comment by crh225** [comment] 2017-06-09 18:03
Are you using Visual Studio 2017?

**Comment by skorunka** [comment] 2017-06-10 08:53
@crh225 I have this setting in my csproj file.

**Comment by m2017atTR** [comment] 2017-06-15 08:57
Ps.
Today again i faced with this problem,

problem was coused by PrimeNg Editor Component, I am not installing with npm using source code of PrimeNg becouse i need some custom needs on their component.

and when i remove Editor/Quill from project HMR runs perfectly...

**Comment by m2017atTR** [comment] 2017-07-03 12:52
this problem hitting again ...
could someone find certain solution ?

**Comment by sylvaincaillot** [comment] 2017-09-21 02:47
I was facing the same issue today with [HMR] bundle rebuilt
Removing "allowJs": true in tsconfig.json made the trick.

**Comment by ExusAltimus** [comment] 2017-10-30 13:37
I was also facing this issue, fixed by removing "declaration": true in tsconfig.json.

**Comment by asadsahi** [comment] 2017-11-04 14:09
tsconfig is a little clean now. so if allowJs was the issue it shouldn't happen anymore. As always I cannot reproduce this. Closing this one until someone ca see this issue again in a specific scenario. Thanks

**Closed by asadsahi** 2017-11-04 14:09 UTC

**Comment by nimishsakalkale** [comment] 2017-11-29 04:59
I am facing this issue.
I am using VS 2107. And I have set allowJS to true. removing allowJS property fixes the issue. but I need this property to be set to true as I need to use some js files (which are not yet converted to typescript).

**Comment by asadsahi** [comment] 2017-11-29 10:10
@nimishsakalkale I am sure you can use javascript file in any project. You somehow need to exclude it from typescript compilation if that isn't the requirement.

try some of the suggestions describe [here](https://github.com/s-panferov/awesome-typescript-loader/issues/502#issuecomment-339857188) and [here](https://github.com/kriasoft/react-starter-kit/issues/1429).

**Comment by nimishsakalkale** [comment] 2017-11-29 14:45
@asadsahi  Adding  `wwwroot `and `ClientApp/dist` to the tsconfig.json exclude list fixed the problem. Thank you.

**Comment by SpaceMonkeyForever** [comment] 2018-01-29 16:49
@nimishsakalkale that was it for me. I don't know why we have to deal with these random bugs.

**Comment by TashaRolland92** [comment] 2018-04-19 09:12
@sylvaincaillot THANKING YOU! New to this and you have saved the day haha
