### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by BitFlipp3r** [asadsahi/AspNetCoreSpa#55] opened 2017-02-16 09:33 UTC
Hi @asadsahi 
Your template is really great, thanks for the hard work!
The only thing missing would be SSR. Do you think it's possible to implement it like [this](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.SpaServices#server-side-prerendering)?
Kind Regards,
Michael

**Comment by asadsahi** [comment] 2017-02-16 09:36
@BitFlipp3r Had some issues with SSR, but not its a little stable, will give it another try.

**Comment by asadsahi** [comment] 2017-03-14 16:58
I dont fully understand SSR or have seen a complete example where there are alot of client side dependencies in an application like this one. How easy SSRS. Help appreciated.

**Comment by patrickgoeler** [comment] 2017-03-29 20:53
Hey @asadsahi, any progress on the SSR?

**Comment by asadsahi** [comment] 2017-03-31 15:55
Still quite complex, no idea. Help welcome. :)

**Comment by asadsahi** [comment] 2017-07-25 15:52
@patrickgoeler @BitFlipp3r I have made some SSR progress in netcore2 branch of this project. But there are few libraries that aren't supported for SSR yet, e.g ng-bootstrap and material2 etc. So thought of updating you guys that those features are coming.

**Comment by BitFlipp3r** [comment] 2017-07-25 17:18
Awesome. Thank you very much for your efforts. Please take your time :)

**Comment by asadsahi** [comment] 2017-11-04 14:06
Hi guys, just to update you on this one. I still can't see a clean way to make it work with SSR. With more features and libraries it breaks on SSR mode. So it is a trade off between having more functionality with 3rd party libraries or getting SSR working in a small demo project. So we'll have to wait until it gets more stability around third party libraries like ng-bootstrap or SignalR etc.

**Comment by isaac2004** [comment] 2018-01-19 17:12
@asadsahi I am intrigued by this project as I contribute to a similar project [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal). I see that you have gotten some basic SSR and SEO concepts to work. Have you had any issues with bundling size or performance issues when doing SSR in production configs?

**Comment by asadsahi** [comment] 2018-01-19 22:34
hi @isaac2004, as of now, SSR work in few basic scenarios and it work in SSR branch of this project as well. 

But, based on my personal experience it isn't as streamlined as it should be. e.g I come across this issues https://github.com/angular/universal/issues/877, for which I have to use --aot flag for SSR build to make it work but the issue is still unanswered. Long discussion for same issue is [here](https://github.com/aspnet/JavaScriptServices/issues/1408). Also, deployment of SSR isn't quick/ideal because of node_modules need to be packaged as part of deployment as explained in [this issue](https://github.com/angular/angular-cli/issues/8616).

**Comment by isaac2004** [comment] 2018-01-20 02:14
I would love for npm to move to a package store like Dot Net Core has. I know it isn't as easy as that, but the need to have node_modules on the server or to bundle and deploy.

**Comment by isaac2004** [comment] 2018-01-20 02:14
I would love for npm to move to a package store like Dot Net Core has. I know it isn't as easy as that, but the need to have node_modules on the server or to bundle and deploy.

**Comment by crh225** [comment] 2018-01-31 01:30
@isaac2004 why do you need node_modules on the server? just curious

**Comment by asadsahi** [comment] 2018-01-31 08:23
For SSR to work 😊

**Comment by crh225** [comment] 2018-01-31 15:35
good to know!

**Comment by Daeamon** [comment] 2018-07-21 13:37
SSR is necessary for SEO optimization (for example, for the correct indexing of your site by search engines)

**Comment by latchezar-kostov-ascendlearning-com** [comment] 2018-07-23 18:35
Fyi, when I enabled SSR, I have seen a few issues:

1. `package.json` npm script `build:ssr`.  I had to change this to `"build:ssr": "ng build --prod --project=ssr"`, as it seems that `"build:ssr": "npm run build --project=ssr"` is just executing `ng build --prod` and the `--project=ssr` parameter doesn't seem to get added onto this command.

2. I seem to have to change `Startup.cs`  `options.BootModulePath = $"{spa.Options.SourcePath}/dist-server/main.bundle.js";` to `options.BootModulePath = $"{spa.Options.SourcePath}/dist-server/main.js";` in order to get this to work.

3. Even after making these changes, when the project is debugged, I receive `NodeInvocationException: Http failure response for (unknown url): 0 Unknown Error`.

**Comment by rezabayesteh** [comment] 2018-08-22 05:58
Please take a look at this example here: [https://github.com/MarkPieszak/aspnetcore-angular2-universal]

**Comment by sajidali2444** [comment] 2018-11-03 10:07
Greate @rezabayesteh can you please share your code.

**Comment by tung238** [comment] 2019-02-27 13:42
> Fyi, when I enabled SSR, I have seen a few issues:
> 
> 1. `package.json` npm script `build:ssr`.  I had to change this to `"build:ssr": "ng build --prod --project=ssr"`, as it seems that `"build:ssr": "npm run build --project=ssr"` is just executing `ng build --prod` and the `--project=ssr` parameter doesn't seem to get added onto this command.
> 2. I seem to have to change `Startup.cs`  `options.BootModulePath = $"{spa.Options.SourcePath}/dist-server/main.bundle.js";` to `options.BootModulePath = $"{spa.Options.SourcePath}/dist-server/main.js";` in order to get this to work.
> 3. Even after making these changes, when the project is debugged, I receive `NodeInvocationException: Http failure response for (unknown url): 0 Unknown Error`.

I think because you running on local host and node did not accept self sign ssl. One way is add this line in to main.server.ts. I was able to see html response after that. However css style not work and elements not show, still figuring out :(

**Comment by tung238** [comment] 2019-02-28 13:24
Btw, this thing is pre-rendering only, not actual server site rendering. It is only able to pre-render index page at build time, other pages still render by client at run time so not really useful.

**Comment by asadsahi** [comment] 2021-11-07 14:55
I think server side rendering in a complex angular app is challenging, especially when there are may external dependencies with SSR issues. and I have decided not to add SSR support in this repo. Hence closing this. Feel free to support in this area for another branch which might be useful for someone. Thanks

**Closed by asadsahi** 2021-11-07 14:55 UTC
Labels: enhancement, help wanted
