### ISSUE TITLE
Unable to publish to IIS using VS2017 Publish

### ISSUE THREAD

**Issue by kiwiingenuity** [asadsahi/AspNetCoreSpa#68] opened 2017-03-21 01:25 UTC
I did the following:
	1. Cloned you application and followed the instructions.
	2. Confirmed that the application worked as expected, which it did.
	3. Opened the project in VS 2017 and set up a publish profile.
	4. Published the application to IIS
	5. View the web site in the browser.  Error 'polyfills_lib' is undefined  Line 982 main.js

I experimented for some time and discovered if I did a "donet publish" from the command line and transferred that repository to IIS then the application worked as expected?

**Comment by asadsahi** [comment] 2017-03-21 22:39
@kiwiingenuity  I have just did few fixes this morning to do publish from visual studio 2017 this morning. This should produce client artifacts while doing publishing from visual studio. Can you confirm if this fixes above issue?

**Comment by asadsahi** [comment] 2017-03-22 10:24
This should be fixed now. There was a problem with csproj file.

**Comment by asadsahi** [comment] 2017-03-22 13:27
Reopening as I can see the issue is still there.

**Comment by asadsahi** [comment] 2017-03-24 15:26
@kiwiingenuity  this should be fixed now. Let me know if you encounter any more errors.

**Closed by asadsahi** 2017-03-24 15:26 UTC
