### ISSUE TITLE
Change bootstrap with @angular/material

### ISSUE THREAD

**Issue by badre429** [asadsahi/AspNetCoreSpa#102] opened 2017-05-14 20:14 UTC
@angular/material keep getting features and it hase huge support from google 
then why not to replace bootstrap with @angular/material

**Comment by skorunka** [comment] 2017-05-15 09:36
This should be optional. The Bootstrap is still the leader on the market. Moreover BS4 should be without any jQuery so it will be more ng-friendly.

**Comment by crh225** [comment] 2017-05-15 14:40
One reason to not use material2 yet is datepicker is still in progress
![image](https://cloud.githubusercontent.com/assets/19475195/26063032/59fa35ac-3952-11e7-9d5f-509cad727865.png)

**Comment by badre429** [comment] 2017-05-15 16:56
the last version @angular/material@2.0.0-beta.5 has initial support for datepicker 
[this is there demo sample ](https://material.angular.io/components/component/datepicker)

**Comment by m2017atTR** [comment] 2017-05-16 12:32
I am using Material 2 and bootstrap together, 
also added some components from source of primeng <- this coused continously hmr build (that I could not solve) so cancelled.

   I suggest to use demo project from Angular Material 2 source ... Thats not bad...

**Comment by skorunka** [comment] 2017-05-18 07:09
@m2017atTR Regarding that HMR issue, did you add primeng to webpack.dev.js:vendor ?

**Comment by m2017atTR** [comment] 2017-05-18 08:13
I dont need whole package , so i added a module named customui
and integrated a few like menu, multi select ext.(as you can see in menu at top, shows demo)

Generally i always work with 2 project, one for experimental and one for distilled :) screen from experimental.

 !!!   I think the problem is i am new at this angular 2+ consept, 
       there is big changes...

**Comment by asadsahi** [comment] 2017-06-02 10:57
UI requirement is different for each project. This project is using bootstrap as an example. Purpose of this project is not to offer various UI libraries, but a complete full stack single page application framework. Closing as it seems out of scope.

**Closed by asadsahi** 2017-06-02 10:57 UTC

**Comment by kanpinar** [comment] 2017-08-17 11:06
So, Can we create another branch for Angular Material 2.... ?
This can be very usefull, i guess.. Material 2 changing very fast and they have new system named CDK
https://github.com/angular/material2/tree/master/src/cdk
